### ISSUE TITLE
Undefined variable $debug_display while preprocessing sass

### ISSUE THREAD

**Issue by davydhaeyer** [roikles/Gridtacular#1]
When I try to preprocess the default demo code I got the following error

>>> Change detected to: sass/_content.scss
      error ../src/sass/_flexbones-grid.scss (Line 421: Undefined variable: "$debug_display".)

**Comment by roikles** [comment]
Hi @davydhaeyer I will take a look at this and see if I can find a quick fix. Gridtacular is still a work in progress, I am currently in the middle of writing unit tests for the grid to ensure that when it is officially released it will be as robust as it is flexible.

**Comment by roikles** [comment]
@davydhaeyer Can you please post the `$grid_args` you used so I can test this further.

**Comment by davydhaeyer** [comment]
I'm trying to change the file in the docs folder. It's still the default _grid-settings.scss file.

My Sass version : 
sass -v
Sass 3.4.21 (Selective Steve)

Command used : 
sass --watch sass:.

**Comment by daemth** [comment]
I followed the provided docs and have the same issue, here are the args I used:
$grid_args: (
        config: (
                gridclass: 'grid',
                columnclass: 'span--'
        ),
        grids: (
                mygrid: (
                        columns: 12,
                        gutter: 2rem
                )
        )
);

**Comment by roikles** [comment]
The issue here is with the way Sass handles variable scope, specifically when variables are set within an `@if` statement they only exist within that scope unless the variable was first define in the parent scope.

I am pushing a fix that should deal with the issue.

**Comment by roikles** [comment]
I believe this is now fixed, feel free to re-open if you have further issues.
